import { supabase, fetchProducts, saveProduct, removeProduct, productFromRow } from './src/supabase.js';

const $ = id => document.getElementById(id);
let products = [], current = null, mediaIndex = 0;
const draftKey = 'orbi9-editor-draft';
const toast = message => { $('toast').textContent = message; $('toast').classList.add('show'); setTimeout(() => $('toast').classList.remove('show'), 2600); };
const imageOf = p => (p.images?.[p.primaryImage || 0] || p.image_url || '/orbi9newlogo.png');
const blank = () => ({ id:'', name:'', subtitle:'', sku:'', category:'', status:'Draft', price:0, quantity:0, description:'', featured:false, trackInventory:true, images:[], primaryImage:0, seo:{title:'',description:''} });

function renderList() {
  const q = $('search').value.trim().toLowerCase(), f = $('filter').value;
  const visible = products.filter(p => (!q || `${p.name} ${p.sku||''} ${p.category||''}`.toLowerCase().includes(q)) && (f === 'all' || p.status === f));
  $('productList').innerHTML = visible.length ? visible.map(p => `<button class="product ${p.id===current?.id?'active':''}" data-id="${p.id}"><img class="thumb" src="${imageOf(p)}" onerror="this.src='/orbi9newlogo.png'"><span><strong>${escapeHtml(p.name || 'Untitled')}</strong><span class="muted">${escapeHtml(p.category || 'Uncategorised')} · $${Number(p.price||0).toFixed(2)}</span></span><span class="badge ${p.status==='Published'?'live':''}">${p.status}</span></button>`).join('') : '<div class="empty">No products found.</div>';
  document.querySelectorAll('.product[data-id]').forEach(b => b.onclick = () => select(products.find(p => p.id === b.dataset.id)));
}
const escapeHtml = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function select(p) { current = p ? structuredClone(p) : blank(); $('formTitle').textContent = current.id ? 'Edit product' : 'New product'; $('deleteBtn').hidden = !current.id; fill(); renderList(); }
function fill() { const p=current; ['name','sku','category','status','price','quantity','subtitle','description'].forEach(k => $(k).value = p[k] ?? ''); $('featured').checked=!!p.featured; $('trackInventory').checked=p.trackInventory!==false; $('images').value=(p.images||[]).map(x=>typeof x==='string'?x:(x.src||x.url||'')).join('\n'); $('seoTitle').value=p.seo?.title||''; $('seoDescription').value=p.seo?.description||''; mediaIndex=0; renderMedia(); $('syncStatus').textContent=p.id?'Loaded from Orbi9 Database':'Unsaved product'; }
function renderMedia() { const images=(current?.images||[]).filter(Boolean); if(mediaIndex>=images.length) mediaIndex=Math.max(0,images.length-1); $('images').value=images.join('\\n'); $('mediaGallery').innerHTML=images.length?images.map((src,i)=>`<div class="media-item ${i===(current.primaryImage||0)?'primary-img':''}"><img src="${escapeHtml(src)}" onerror="this.style.opacity='.35'"><button type="button" class="secondary" data-primary="${i}">${i===(current.primaryImage||0)?'★ Featured':'Make featured'}</button><button type="button" class="danger" data-remove="${i}">Remove</button></div>`).join(''):'<p class="hint">No images added yet.</p>'; document.querySelectorAll('[data-primary]').forEach(b=>b.onclick=()=>{current.primaryImage=Number(b.dataset.primary);mediaIndex=current.primaryImage;renderMedia();}); document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{current.images.splice(Number(b.dataset.remove),1);current.primaryImage=Math.min(current.primaryImage||0,Math.max(0,current.images.length-1));renderMedia();}); const carousel=$('mediaCarousel'); carousel.style.display=images.length?'block':'none'; if(images.length){$('carouselImage').src=images[mediaIndex];$('mediaPosition').textContent=`${mediaIndex+1} / ${images.length}`;} }
async function uploadImages(files) { if(!current) return; $('syncStatus').textContent='Uploading images…'; try { for(const file of files){ const safe=file.name.toLowerCase().replace(/[^a-z0-9.]+/g,'-'); const path=`products/${crypto.randomUUID()}-${safe}`; const {error}=await supabase.storage.from('product-images').upload(path,file,{upsert:false,contentType:file.type}); if(error) throw error; const {data}=supabase.storage.from('product-images').getPublicUrl(path); current.images.push(data.publicUrl); } renderMedia(); $('syncStatus').textContent='Images uploaded — save the product to keep them'; toast(`${files.length} image${files.length===1?'':'s'} uploaded`); } catch(e) { $('syncStatus').textContent=`Upload failed: ${e.message}`; toast('Image storage is not ready yet — contact your administrator'); } }
function readForm() { return {...current, name:$('name').value.trim(), sku:$('sku').value.trim(), category:$('category').value.trim(), status:$('status').value, price:Number($('price').value||0), quantity:Math.max(0,Number($('quantity').value||0)), subtitle:$('subtitle').value.trim(), description:$('description').value.trim(), featured:$('featured').checked, trackInventory:$('trackInventory').checked, images:$('images').value.split('\n').map(x=>x.trim()).filter(Boolean), primaryImage:0, seo:{title:$('seoTitle').value.trim(),description:$('seoDescription').value.trim()} }; }
async function refresh() { $('syncStatus').textContent='Loading catalogue…'; try { products=await fetchProducts(); localStorage.setItem('orbi9-catalog-v2',JSON.stringify(products)); $('syncStatus').textContent=`${products.length} products synced`; renderList(); if(!current) select(products[0]); } catch(e) { $('syncStatus').textContent=`Database error: ${e.message}`; toast('Could not load the Orbi9 inventory'); } }
async function submit(e) { e.preventDefault(); const p=readForm(); if(!p.name) return; $('syncStatus').textContent='Saving…'; try { const saved=await saveProduct(p); products=[saved,...products.filter(x=>x.id!==saved.id)]; current=saved; localStorage.setItem('orbi9-catalog-v2',JSON.stringify(products)); $('syncStatus').textContent='Saved to Orbi9 Database'; $('formTitle').textContent='Edit product'; $('deleteBtn').hidden=false; renderList(); toast('Product saved'); } catch(e) { $('syncStatus').textContent=`Save failed: ${e.message}`; toast('Save failed — check your inventory access'); } }
async function remove() { if(!current?.id || !confirm(`Delete “${current.name}”? This cannot be undone.`)) return; try { await removeProduct(current.id); products=products.filter(x=>x.id!==current.id); current=null; select(products[0]); toast('Product deleted'); } catch(e) { toast(`Delete failed: ${e.message}`); } }
function exportData() { const blob=new Blob([JSON.stringify(products,null,2)],{type:'application/json'}), a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=`orbi9-products-${new Date().toISOString().slice(0,10)}.json`; a.click(); URL.revokeObjectURL(a.href); }
async function importData(file) { try { const incoming=JSON.parse(await file.text()); if(!Array.isArray(incoming)) throw Error('Expected a JSON array'); for(const p of incoming) await saveProduct({...blank(),...p,id:''}); await refresh(); toast(`${incoming.length} products imported`); } catch(e) { toast(`Import failed: ${e.message}`); } }
async function boot() { const {data:{session}}=await supabase.auth.getSession(); if(session) showStudio(); }
function showStudio() { $('login').hidden=true; $('studio').hidden=false; refresh(); }
$('loginForm').onsubmit=async e=>{e.preventDefault(); $('loginError').textContent='Signing in…'; const {error}=await supabase.auth.signInWithPassword({email:$('email').value,password:$('password').value}); if(error) $('loginError').textContent=error.message; else showStudio();};
$('signOut').onclick=async()=>{await supabase.auth.signOut(); location.reload();}; document.querySelectorAll('[data-tab]').forEach(tab=>tab.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===tab));document.querySelectorAll('[data-panel]').forEach(panel=>panel.hidden=panel.dataset.panel!==tab.dataset.tab);}); $('newBtn').onclick=()=>select(null); $('imageFiles').onchange=e=>e.target.files?.length&&uploadImages([...e.target.files]); $('mediaPrev').onclick=()=>{if(current?.images?.length){mediaIndex=(mediaIndex+current.images.length-1)%current.images.length;renderMedia();}}; $('mediaNext').onclick=()=>{if(current?.images?.length){mediaIndex=(mediaIndex+1)%current.images.length;renderMedia();}}; $('productForm').onsubmit=submit; $('deleteBtn').onclick=remove; $('resetBtn').onclick=()=>select(current?.id?products.find(p=>p.id===current.id):null); $('search').oninput=renderList; $('filter').onchange=renderList; $('exportBtn').onclick=exportData; $('importBtn').onclick=()=>$('importFile').click(); $('importFile').onchange=e=>e.target.files[0]&&importData(e.target.files[0]);
boot();
